security:
  
    encoders:
        AppBundle\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\User:
                    algorithm: bcrypt
                    cost: 12

    providers:
        chain_provider:
                chain:
                    providers: [our_users]
        our_users:
                  entity: {class: AppBundle\Entity\User, property: email}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout_on_user_change: true
            provider: our_users
            guard:
                authenticator:
                   - AppBundle\Security\LoginFormAuthenticator
                   - AppBundle\Security\FacebookAuthenticator
                entry_point: AppBundle\Security\LoginFormAuthenticator

            logout:
              path: /logout

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api/admin, roles: ROLE_ADMIN }
